#服务后台
server:
  port: 8080
  servlet:
    context-path: /test
spring:
  #数据源
  datasource:
    dynamic:
      primary: db0
      datasource:
        db0:
          url: jdbc:mysql://172.16.25.20:3306/lg_zhcs?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
          username: root
          password: 12345678
          driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: select 1 from dual
  rabbitmq:
    host: 121.4.61.136
    port: 5672
    virtual-host: /test
    username: test
    password: test
    publisher-confirms: true #消息发送到交换器确认
    publisher-returns: true #消息发送到队列确认
mybatis-plus:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.example.demo.entity
  check-config-location: true
  #configuration:
  #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
